// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Вход для создания задачи. description необязателен.
type CreateTaskInput struct {
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

// Вход для частичного обновления. Все поля необязательны:
// поле, переданное как null/опущенное, не меняет текущее значение.
type UpdateTaskInput struct {
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	Done        *bool   `json:"done,omitempty"`
}
