package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"errors"

	"prac_13/services/graphql/graph/generated"
	"prac_13/services/graphql/graph/model"
	"prac_13/services/graphql/internal/service"
)

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input model.CreateTaskInput) (*service.Task, error) {
	task, err := r.TaskSvc.Create(ctx, service.CreateTaskRequest{
		Title:       input.Title,
		Description: derefString(input.Description),
	})
	if err != nil {
		if errors.Is(err, service.ErrValidation) {
			return nil, errors.New("title is required")
		}
		return nil, errors.New("internal error")
	}
	return &task, nil
}

// UpdateTask is the resolver for the updateTask field.
func (r *mutationResolver) UpdateTask(ctx context.Context, id string, input model.UpdateTaskInput) (*service.Task, error) {
	task, err := r.TaskSvc.Update(ctx, id, service.UpdateTaskRequest{
		// Указатели пробрасываются как есть: nil-поле сервис не трогает,
		// поэтому частичное обновление работает "из коробки".
		Title:       input.Title,
		Description: input.Description,
		Done:        input.Done,
	})
	if err != nil {
		switch {
		case errors.Is(err, service.ErrNotFound):
			return nil, errors.New("task not found")
		case errors.Is(err, service.ErrValidation):
			return nil, errors.New("title cannot be empty")
		default:
			return nil, errors.New("internal error")
		}
	}
	return &task, nil
}

// DeleteTask is the resolver for the deleteTask field.
func (r *mutationResolver) DeleteTask(ctx context.Context, id string) (bool, error) {
	// По методичке стабильнее вернуть false, если задача не найдена, чем ронять
	// операцию ошибкой. Прочие (инфраструктурные) ошибки — уже GraphQL error.
	err := r.TaskSvc.Delete(ctx, id)
	if errors.Is(err, service.ErrNotFound) {
		return false, nil
	}
	if err != nil {
		return false, errors.New("internal error")
	}
	return true, nil
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context) ([]*service.Task, error) {
	tasks, err := r.TaskSvc.List(ctx)
	if err != nil {
		return nil, errors.New("internal error")
	}
	return toPointers(tasks), nil
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id string) (*service.Task, error) {
	task, err := r.TaskSvc.Get(ctx, id)
	if err != nil {
		// Не найдена — возвращаем null (а не ошибку), сервер при этом не падает.
		if errors.Is(err, service.ErrNotFound) {
			return nil, nil
		}
		return nil, errors.New("internal error")
	}
	return &task, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// derefString разыменовывает необязательную строку входа (nil → "").
func derefString(s *string) string {
	if s == nil {
		return ""
	}
	return *s
}

// toPointers переводит []Task в []*Task, как ожидают сигнатуры резолверов,
// сгенерированные gqlgen для списка [Task!]!.
func toPointers(tasks []service.Task) []*service.Task {
	out := make([]*service.Task, len(tasks))
	for i := range tasks {
		t := tasks[i]
		out[i] = &t
	}
	return out
}
